import type { Metadata } from 'next';
import localFont from 'next/font/local';

import './globals.css';
import Header from '@/components/Header';
import Footer from '@/components/Footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const consolas = localFont({
  src: [
    {
      path: '../fonts/consola.ttf',
      weight: '400',
      style: 'normal',
    },
  ],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={consolas.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
